### ISSUE TITLE
Target display mode not detected whatsoever

### ISSUE THREAD

**Issue by JamesHortonLtd** [duanefields/VirtualKVM#57]
I have a Mid 2015 MacBook Pro connected to a Mid 2011 iMac using a new thunderbolt cable. Both macs are running High Sierra and Virtual KVM is on the iMac. The iMac is not detected when connected to the MacBook Pro as a second display. Any ideas?

**Comment by SoneeJohn** [comment]
@JamesHortonLtd Will be releasing a new version soon that should fix this

**Comment by SoneeJohn** [comment]
@JamesHortonLtd Please see if the latest version fixed you issue [here](https://github.com/duanefields/VirtualKVM/releases/download/v1.2.4/v1_2_4.zip)

**Comment by runar-rkmedia** [comment]
I have a 2012 iMac and 2015 MacBook Pro, same problem with this version (1.2.4)

**Comment by JamesHortonLtd** [comment]
Thanks, Sonee John sorry for the very late reply. The update did not fix the problem. 
Apple have had a look at both the MacBook Pro and the iMac, they think there could be an issue with the iMac Thunderbolt port? However, we got it to connect and mirror to an external monitor using TDM in store. But the system info doesn't say it's connected? I'm inclined to think it could be an OS issue maybe high sierra doesn't support TDM? But I have yet to install an Earlier OS to test this. Thanks, James

**Comment by ghost** [comment]
I’m having a similar issue with MacBook Pro (Late 2013, Mojave) and iMac (Mid 2011, High Sierra). Replacing keyboard events with ‘Brightness Up’ sysdef event seems to fix this.

Of course, I’m kinda wary of making a PR before asking: is there any particular reason sending `0x90` was preferred to sysdef events?
